spring.application.name: reservation

spring:
  datasource:
    url: jdbc:mysql://192.168.35.179:3306/reservation
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: master
    password: master

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  main:
    web-application-type: none